server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.1.102:3306/webpj?serverTimezone=GMT%2B8
    username: liuhui
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: mapper/*.xml